cloudfront_public_key = <<-EOT
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsxmpLgMJnOOzyf0INJVk
+1ryc2iwi+3TVcUWE1oFT4yniLoI4Ud7Vh9zLXXTSiUOuEkN9Gqe3jIxrjcxToxl
f7IhvVWflTWVyFkkHlfG39ODZYNyo3xrUbOD9dZUBEsyIF7Z+M7R8ueFuZqylIZV
sk22gVwZVXurPqWdny7jIbytY0fnaO+R1AyQcCVwncI+6eZmv0OD3d3mWJpSjXhc
2WmqUKVZt+dOudlaFXxqjY9bKjqW4Xbh04+zJlfNG//1DVzamXkDufnitI4bA0Q2
BsIs9oKWU2htUauDAkYQamwDrJEdbFwjrx8y1kmLoO9zDhrmTRUWPKwdpVLLnwTK
aQIDAQAB
-----END PUBLIC KEY-----
EOT
