name: 'Publish site'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish-site.yml'
      - 'src/**'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::075673041815:role/external/deployer
      - name: AWS S3 sync
        run: aws s3 sync --delete src s3://example.melvyn.dev
